name: Update gist with WakaTime stats
on:
  schedule:
    - cron: '30 18 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: dcdbff543ffc14ef2fb2eb15304f47ae
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
